#!/usr/bin/env python2
import sys
import os

command_template = "ansible-playbook playbooks/{0}.yml -i inventories/{1}/inventory"

def main():
    if len(sys.argv) == 1:
        print("Usage:%s [provision | prepare | build | deploy] [local | staging | prod]" % sys.argv[0])
        return

    phase = sys.argv[1]
    env = sys.argv[2]

    os.system(command_template.format(phase, env))
    
if __name__ == '__main__':
    main()

