---
galaxy_info:
  author: Yan Zhou
  description: Apt repository sources.list configuration for Ubuntu.
  company: digizen
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - lucid
    - maverick
    - natty
    - oneiric
    - precise
    - quantal
    - raring
    - saucy
    - trusty
    - utopic
    - vivid
  categories:
  - system
dependencies: []
